#!/usr/bin/env python3
"""
Raspberry Pi Meshtastic to Supabase Live Data Uploader (FIXED VERSION)

Standalone script that reads live Meshtastic telemetry from CSV files
generated by rpi_log_script.py and uploads directly to Supabase.

FIXED: Properly reads CSV files from the actual data directory structure
"""

import os
import sys
import json
import time
import requests
import logging
from datetime import datetime, timezone, timedelta
from typing import Dict, List, Optional, Any
import threading
import signal
import uuid
import csv
import glob
from collections import defaultdict

# Configuration - Set via environment variables or modify here
SUPABASE_URL = os.getenv('SUPABASE_URL', 'https://vanqyqnugswokfchdhpk.supabase.co')
SUPABASE_SERVICE_KEY = os.getenv('SUPABASE_SERVICE_KEY', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhbnF5cW51Z3N3b2tmY2hkaHBrIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MDcwMTQ0MSwiZXhwIjoyMDY2Mjc3NDQxfQ.iWDU9-lOzMRn_nFwP7izNRTsOxY8trVRFY-lVw7TaY4')
API_BASE_URL = os.getenv('API_BASE_URL', '')
DATA_DIR = os.getenv('DATA_DIR', '/home/pi/Documents/smesh/snode')
POLL_INTERVAL_SEC = int(os.getenv('POLL_INTERVAL_SEC', '60'))
UPLOAD_BATCH_SIZE = int(os.getenv('UPLOAD_BATCH_SIZE', '10'))
UPLOAD_INTERVAL_SEC = int(os.getenv('UPLOAD_INTERVAL_SEC', '30'))
DEBUG = os.getenv('DEBUG', 'true').lower() == 'true'

# Setup logging
log_level = logging.DEBUG if DEBUG else logging.INFO
logging.basicConfig(
    level=log_level,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler('/home/pi/Documents/smesh/snode/data/meshtastic_upload.log'),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger('MeshtasticUploader')

class MeshtasticTelemetryUploader:
    """
    Handles receiving Meshtastic telemetry and uploading to Supabase
    """
    
    def __init__(self):
        self.upload_queue = []
        self.queue_lock = threading.Lock()
        self.upload_session = requests.Session()
        self.running = True
        self.last_upload = datetime.now()
        self.total_uploaded = 0
        self.last_read_positions = defaultdict(int)
        
        # Configure session headers
        if SUPABASE_SERVICE_KEY:
            self.upload_session.headers.update({
                'Authorization': f'Bearer {SUPABASE_SERVICE_KEY}',
                'apikey': SUPABASE_SERVICE_KEY,
                'Content-Type': 'application/json',
                'User-Agent': 'RaspberryPi-Meshtastic-Uploader/1.0'
            })
        
        # Start upload worker thread
        self.upload_thread = threading.Thread(target=self._upload_worker, daemon=True)
        self.upload_thread.start()
        
        logger.info(f"Initialized uploader - API: {API_BASE_URL or 'Direct Supabase'}")
    
    def find_latest_data_dirs(self):
        """Find all data directories that match the pattern"""
        data_dirs = glob.glob(os.path.join(DATA_DIR, 'data-*'))
        logger.debug(f"Found data directories: {data_dirs}")
        return sorted(data_dirs, key=os.path.getmtime, reverse=True)  # Most recent first

    def find_csv_files_in_dir(self, data_dir):
        """Find all CSV files in a data directory and its subdirectories"""
        csv_files = []
        
        # Look for CSV files directly in the data directory
        csv_pattern = os.path.join(data_dir, '*.csv')
        csv_files.extend(glob.glob(csv_pattern))
        
        # Look for CSV files in subdirectories (like f864/)
        for root, dirs, files in os.walk(data_dir):
            for file in files:
                if file.endswith('.csv') and any(metric in file for metric in ['environmentMetrics', 'airQualityMetrics', 'deviceMetrics', 'powerMetrics']):
                    csv_files.append(os.path.join(root, file))
        
        logger.debug(f"Found CSV files in {data_dir}: {csv_files}")
        return csv_files

    def _poll_once(self):
        """Poll for new CSV data and process it"""
        try:
            logger.info("Starting data poll...")
            data_dirs = self.find_latest_data_dirs()
            
            if not data_dirs:
                logger.warning(f"No data directories found in {DATA_DIR}")
                return
            
            # Process the most recent 3 data directories to catch recent data
            for data_dir in data_dirs[:3]:
                logger.info(f"Processing data directory: {data_dir}")
                csv_files = self.find_csv_files_in_dir(data_dir)
                
                if not csv_files:
                    logger.info(f"No CSV files found in {data_dir}")
                    continue
                
                for csv_file in csv_files:
                    logger.info(f"Processing CSV file: {csv_file}")
                    self._process_csv_file(csv_file)
                    
        except Exception as e:
            logger.error(f'Poll error: {e}', exc_info=True)

    def _process_csv_file(self, csv_file):
        """Process a single CSV file and extract telemetry data"""
        try:
            if not os.path.exists(csv_file):
                logger.warning(f"CSV file not found: {csv_file}")
                return

            # Determine telemetry type from filename
            telemetry_type = self._get_telemetry_type_from_filename(csv_file)
            if not telemetry_type:
                logger.warning(f"Cannot determine telemetry type from filename: {csv_file}")
                return

            with open(csv_file, 'r') as f:
                f.seek(0, os.SEEK_END)
                file_size = f.tell()
                last_pos = self.last_read_positions[csv_file]
                
                if last_pos >= file_size:
                    logger.debug(f"No new data in {csv_file}")
                    return
                
                f.seek(last_pos)
                reader = csv.reader(f)
                
                # Skip header if reading from beginning
                if last_pos == 0:
                    try:
                        header = next(reader)
                        logger.debug(f"CSV header: {header}")
                    except StopIteration:
                        return

                rows_processed = 0
                for row in reader:
                    if row and len(row) > 2:  # Ensure we have enough columns
                        telemetry = self._parse_csv_row_to_telemetry(row, telemetry_type)
                        if telemetry:
                            with self.queue_lock:
                                self.upload_queue.append(telemetry)
                            rows_processed += 1
                
                self.last_read_positions[csv_file] = file_size
                logger.info(f"Processed {rows_processed} new rows from {csv_file}")
                
        except Exception as e:
            logger.error(f'Error processing CSV file {csv_file}: {e}', exc_info=True)

    def _get_telemetry_type_from_filename(self, filename):
        """Determine telemetry type from CSV filename"""
        basename = os.path.basename(filename).lower()
        if 'environmentmetrics' in basename:
            return 'environment'
        elif 'airqualitymetrics' in basename:
            return 'air_quality'
        elif 'devicemetrics' in basename:
            return 'device'
        elif 'powermetrics' in basename:
            return 'power'
        return None

    def _parse_csv_row_to_telemetry(self, row, telemetry_type):
        """Parse a CSV row into telemetry data for upload"""
        try:
            if len(row) < 3:
                return None
                
            timestamp_str = row[0]
            node_id = row[1].replace('0x', '')  # Strip 0x if present
            
            # Parse timestamp
            try:
                timestamp = datetime.fromisoformat(timestamp_str.replace('Z', '+00:00'))
            except ValueError:
                timestamp = datetime.now(timezone.utc)
            
            # Base telemetry structure
            telemetry_data = {
                'sensor_id': node_id,
                'timestamp': timestamp.isoformat(),
                'telemetry_type': telemetry_type,
                'location': None,
                'voltage': None,
                'battery_level': None,
                'air_util_tx': None,
                'uptime_seconds': None,
                'channel_utilization': None,
                'temperature_c': None,
                'relative_humidity_pct': None,
                'barometric_pressure': None,
                'gas_resistance': None,
                'iaq': None,
                'wind_direction': None,
                'wind_speed': None,
                'pm25_ugm3': None,
                'pm10_ugm3': None,
                'pm100_ugm3': None,
                'pm1_ugm3': None,
                'ch3_voltage': None,
                'ch3_current': None,
                'rssi': None,
                'snr': None,
                'hop_limit': None,
                'hop_start': None,
                'raw_data': {}
            }
            
            # Parse specific metrics based on type and available columns
            if telemetry_type == 'environment' and len(row) >= 9:
                telemetry_data.update({
                    'temperature_c': self._safe_float(row[2]),
                    'relative_humidity_pct': self._safe_float(row[3]),
                    'barometric_pressure': self._safe_float(row[4]),
                    'gas_resistance': self._safe_float(row[5]),
                    'iaq': self._safe_float(row[6]),
                    'wind_direction': self._safe_float(row[7]),
                    'wind_speed': self._safe_float(row[8]),
                })
                # Signal strength data
                if len(row) > 9:
                    telemetry_data.update({
                        'snr': self._safe_float(row[9]),
                        'rssi': self._safe_float(row[10]),
                    })
                    
            elif telemetry_type == 'air_quality' and len(row) >= 8:
                telemetry_data.update({
                    'pm10_ugm3': self._safe_float(row[2]),
                    'pm25_ugm3': self._safe_float(row[3]),
                    'pm100_ugm3': self._safe_float(row[4]),
                    'pm1_ugm3': self._safe_float(row[5]),  # pm10Environmental as PM1
                })
                # Signal strength data
                if len(row) > 8:
                    telemetry_data.update({
                        'snr': self._safe_float(row[8]),
                        'rssi': self._safe_float(row[9]),
                    })
                    
            elif telemetry_type == 'device' and len(row) >= 6:
                telemetry_data.update({
                    'battery_level': self._safe_int(row[2]),
                    'voltage': self._safe_float(row[3]),
                    'channel_utilization': self._safe_float(row[4]),
                    'air_util_tx': self._safe_float(row[5]),
                })
                
            elif telemetry_type == 'power' and len(row) >= 4:
                telemetry_data.update({
                    'ch3_voltage': self._safe_float(row[2]),
                    'ch3_current': self._safe_float(row[3]),
                })
            
            # Store raw row data for debugging
            telemetry_data['raw_data'] = {f'col_{i}': val for i, val in enumerate(row)}
            
            return telemetry_data
            
        except Exception as e:
            logger.error(f'Error parsing CSV row: {e}', exc_info=True)
            return None

    def _safe_float(self, value):
        """Safely convert value to float"""
        try:
            return float(value) if value and value.strip() else None
        except (ValueError, AttributeError):
            return None

    def _safe_int(self, value):
        """Safely convert value to int"""
        try:
            return int(float(value)) if value and value.strip() else None
        except (ValueError, AttributeError):
            return None
    
    def _upload_worker(self):
        """Background worker that uploads queued data"""
        while self.running:
            try:
                time.sleep(UPLOAD_INTERVAL_SEC)
                
                with self.queue_lock:
                    if len(self.upload_queue) == 0:
                        continue
                    
                    # Take a batch for upload
                    batch = self.upload_queue[:UPLOAD_BATCH_SIZE]
                    del self.upload_queue[:UPLOAD_BATCH_SIZE]
                
                if batch:
                    self._upload_batch(batch)
                    
            except Exception as e:
                logger.error(f"Upload worker error: {e}", exc_info=True)
                time.sleep(5)
    
    def _upload_batch(self, batch: List[Dict]):
        """Upload a batch of telemetry data to Supabase"""
        if not batch:
            return
            
        logger.info(f"Uploading batch of {len(batch)} telemetry records...")
        
        try:
            # Direct PostgREST insert into Supabase
            url = f"{SUPABASE_URL.rstrip('/')}/rest/v1/meshtastic_telemetry"
            response = self.upload_session.post(url, json=batch, timeout=30)
            
            if response.status_code in (200, 201):
                self.total_uploaded += len(batch)
                self.last_upload = datetime.now()
                logger.info(f"✅ Upload successful ({response.status_code}) - Total uploaded: {self.total_uploaded}")
            else:
                logger.error(f"❌ Upload failed: {response.status_code} - {response.text}")
                # Re-queue failed items
                with self.queue_lock:
                    self.upload_queue.extend(batch)
                    
        except requests.exceptions.RequestException as e:
            logger.error(f"❌ Network error during upload: {e}")
            # Re-queue failed items
            with self.queue_lock:
                self.upload_queue.extend(batch)
        except Exception as e:
            logger.error(f"❌ Unexpected upload error: {e}", exc_info=True)
    
    def get_stats(self) -> Dict[str, Any]:
        """Get current upload statistics"""
        with self.queue_lock:
            queue_size = len(self.upload_queue)
        
        return {
            'queue_size': queue_size,
            'total_uploaded': self.total_uploaded,
            'last_upload': self.last_upload.isoformat() if self.last_upload else None,
            'upload_thread_alive': self.upload_thread.is_alive()
        }
    
    def shutdown(self):
        """Gracefully shutdown the uploader"""
        logger.info("Shutting down uploader...")
        self.running = False
        
        # Upload remaining items
        with self.queue_lock:
            if self.upload_queue:
                logger.info(f"Uploading final {len(self.upload_queue)} items...")
                self._upload_batch(self.upload_queue)
                self.upload_queue.clear()
        
        # Wait for upload thread to finish
        if self.upload_thread.is_alive():
            self.upload_thread.join(timeout=10)

def signal_handler(signum, frame):
    """Handle shutdown signals"""
    logger.info(f"Received signal {signum}, shutting down...")
    global uploader
    if uploader:
        uploader.shutdown()
    sys.exit(0)

def main():
    """Main entry point"""
    logger.info("🚀 Starting Raspberry Pi Meshtastic to Supabase Uploader (FIXED VERSION)")
    logger.info(f"  Data Directory: {DATA_DIR}")
    logger.info(f"  Poll Interval: {POLL_INTERVAL_SEC}s")
    logger.info(f"  API Base: {API_BASE_URL or 'Direct Supabase'}")
    logger.info(f"  Upload Interval: {UPLOAD_INTERVAL_SEC}s")
    logger.info(f"  Batch Size: {UPLOAD_BATCH_SIZE}")
    logger.info(f"  Debug Mode: {DEBUG}")
    
    if not SUPABASE_SERVICE_KEY:
        logger.error("❌ SUPABASE_SERVICE_KEY environment variable required")
        sys.exit(1)
    
    # Check data directory
    if not os.path.exists(DATA_DIR):
        logger.error(f"❌ Data directory {DATA_DIR} not found")
        sys.exit(1)
    
    # Setup signal handlers
    signal.signal(signal.SIGINT, signal_handler)
    signal.signal(signal.SIGTERM, signal_handler)
    
    # Initialize components
    global uploader
    uploader = MeshtasticTelemetryUploader()
    
    # Start polling and processing
    uploader._poll_once()
    
    # Show stats
    stats = uploader.get_stats()
    logger.info(f"📊 Final stats: {stats}")
    
    # Wait for uploads to complete if data was found
    if stats['queue_size'] > 0:
        logger.info(f"⏳ Waiting for {stats['queue_size']} items to upload...")
        time.sleep(UPLOAD_INTERVAL_SEC + 10)
    
    uploader.shutdown()
    logger.info("✅ Upload process complete")

if __name__ == "__main__":
    main()